### ISSUE TITLE
Exception is thrown when making a new line

### ISSUE THREAD

**Issue by AlphaNecron** [AvaloniaUI/AvaloniaEdit#199]
https://user-images.githubusercontent.com/57827456/151944341-eb60bc5f-dbfc-470b-8f99-5baa23ee350c.mp4

This happens only when I add `tm.SetGrammar(ropts.GetScopeByLanguageId(ropts.GetLanguageByExtension(".cs").Id));`

Is there any solution?

**Comment by AlphaNecron** [comment]
Stacktrace:
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at TextMateSharp.Model.AbstractLineList.Get(Int32 index) in /_/src/TextMateSharp/Model/AbstractLineList.cs:line 37
   at TextMateSharp.Model.TMModel.TokenizerThread.ThreadWorker() in /_/src/TextMateSharp/Model/TMModel.cs:line 97
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by danipen** [comment]
@AlphaNecron. I tried the demo application and I cannot reproduce it.

Could you share a minimal sample that reproduces the issue? I'll try to fix. Thanks in advance

**Comment by AlphaNecron** [comment]
Can i send the project to your email?

**Comment by danipen** [comment]
Well, just share here how you instantiate the Avalonia Text Editor and how you set up TextMate just to help me to reproduce the issue.

**Comment by AlphaNecron** [comment]
```xaml
       <avaloniaEdit:TextEditor x:Name="MainEditor" Padding="4"
                                 Background="#181818"
                                 HorizontalScrollBarVisibility="Auto"
                                 VerticalScrollBarVisibility="Auto"
                                 FontFamily="avares://Kide/Assets/Fonts#JetBrains Mono"
                                 FontWeight="Normal"
                                 FontSize="13"
                                 Encoding="{Binding EditorEncoding, Mode=TwoWay}"
                                 WordWrap="False" ShowLineNumbers="True">
            <avaloniaEdit:TextEditor.Options>
                <avaloniaEdit:TextEditorOptions EnableHyperlinks="True" ConvertTabsToSpaces="True" ShowSpaces="True" EnableRectangularSelection="True" HighlightCurrentLine="True"/>
            </avaloniaEdit:TextEditor.Options>
            <avaloniaEdit:TextEditor.ContextMenu>
                <ContextMenu>
                    <MenuItem Header="Cut">
                        <MenuItem.Icon>
                            <PathIcon Width="12" Height="12" Data="{StaticResource CutGeometry}"/>
                        </MenuItem.Icon>
                    </MenuItem>
                </ContextMenu>
            </avaloniaEdit:TextEditor.ContextMenu>
            <Interaction.Behaviors>
                <behaviors:DocumentTextBindingBehavior Text="{Binding Code, Mode=TwoWay}" />
            </Interaction.Behaviors>
        </avaloniaEdit:TextEditor>
```
```csharp
            var ropts = new RegistryOptions(ThemeName.DarkPlus);
            var editor = this.FindControl<TextEditor>("MainEditor");
            editor.TextArea.Caret.PositionChanged += delegate
            {
                ViewModel!.CaretPos = editor.TextArea.Caret.Position.Location;
            };
            editor.TextArea.SelectionBrush = new SolidColorBrush
            {
                Color = Color.FromRgb(38, 78, 119),
                Opacity = 0.4
            };
            editor.TextArea.SelectionCornerRadius = 2;
            editor.TextArea.SelectionForeground = new SolidColorBrush
            {
                Color = Color.FromRgb(248, 250, 251)
            };
            editor.TextArea.IndentationStrategy = new CSharpIndentationStrategy();
            var tm = editor.InstallTextMate(ropts);
            tm.SetGrammar(ropts.GetScopeByLanguageId(ropts.GetLanguageByExtension(".pas").Id));
            tm.SetTheme(ropts.LoadTheme(ThemeName.DarkPlus));
```

**Comment by danipen** [comment]
I'm sorry I'm unable to reproduce the issue. Can you reproduce the issue in the "Demo" application?

**Comment by danipen** [comment]
I cannot:

https://user-images.githubusercontent.com/501613/151955836-f4b82ed4-5f59-4611-b709-7dc46953b59b.mp4

**Comment by AlphaNecron** [comment]
https://github.com/AlphaNecron/Kide Here's the repo, you can try and see.

**Comment by danipen** [comment]
Reproduced using your sample. I'll provide a fix for it. 

Note that [re-setting the document text here](https://github.com/AlphaNecron/Kide/blob/47f0607904f47a1cc8239a2198893d09c517a365/Kide/Behaviors/DocumentTextBindingBehavior.cs#L56) makes editing incredible slow (and that unveiled a sync issue in TextMateSharp).

**Comment by AlphaNecron** [comment]
> Reproduced using your sample. I'll provide a fix for it.
> 
> Note that [re-setting the document text here](https://github.com/AlphaNecron/Kide/blob/47f0607904f47a1cc8239a2198893d09c517a365/Kide/Behaviors/DocumentTextBindingBehavior.cs#L56) makes editing incredible slow (and that unveiled a sync issue in TextMateSharp).

It's a part of the MVVM example of `AvaloniaEdit` tho.

**Comment by AlphaNecron** [comment]
> Note that [re-setting the document text here](https://github.com/AlphaNecron/Kide/blob/47f0607904f47a1cc8239a2198893d09c517a365/Kide/Behaviors/DocumentTextBindingBehavior.cs#L56) makes editing incredible slow (and that unveiled a sync issue in TextMateSharp).

Is there another way to do this?

**Comment by danipen** [comment]
Sorry I'm not aware about the MVVM sample of avalonia edit. @Takoooooo can you help with this?
