### ISSUE TITLE
Add support for webassembly

### ISSUE THREAD

**Issue by wieslawsoltes** [AvaloniaUI/AvaloniaEdit#201]
When trying to run on webassembly I get the following exception:
```
Unhandled exception rendering component: Operation is not supported on this platform.
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Threading.Thread.Start()
   at TextMateSharp.Model.TMModel.TokenizerThread.Run() in /_/src/TextMateSharp/Model/TMModel.cs:line 63
   at TextMateSharp.Model.TMModel.Start() in /_/src/TextMateSharp/Model/TMModel.cs:line 334
   at TextMateSharp.Model.TMModel.SetGrammar(IGrammar grammar) in /_/src/TextMateSharp/Model/TMModel.cs:line 282
   at AvaloniaEdit.TextMate.TextMateColoringTransformer.SetGrammar(IGrammar grammar)
   at AvaloniaEdit.TextMate.TextMate.Installation.SetGrammar(String scopeName)
```

**Comment by Numpsy** [comment]
I haven't tried to get syntax highlighting going in the latest Avalonia 11 previews, but fwiw I've tried the build from https://github.com/AvaloniaUI/AvaloniaEdit/pull/318 with 11p6 and both folding and searching are working fine.

One small comment about the searching though - the search panel opens up immediately when pressing ctrl+f, but there is a noticable lag between starting to type into the search box and anything happening with the search as compared to desktop app usage. (I haven't made an attempt at working out what's taking the time)

**Comment by Gillibald** [comment]
Keep in mind wasm does not support threading at the moment so you will not get any background processing

**Comment by Numpsy** [comment]
I at one point had a go a building eveything with ```WasmEnableThreads``` but couldn't get it working at the time, I keep meaning to have another go and haven't got to it yet :-(

**Comment by danipen** [comment]
Does .net7 support threads by default in wasm? or not yet?
