### ISSUE TITLE
TextFormatter rework issues

### ISSUE THREAD

**Issue by Gillibald** [AvaloniaUI/AvaloniaEdit#243]

**Comment by Gillibald** [comment]
@danipen
- [ ] Long lines support is broken again. Editing/selection/going home-end in very long line is super slow. You can find a [test file](https://github.com/danipen/TextMateSharp/blob/master/src/TextMateSharp.Demo/testdata/samplefiles/bigfile_single_line.cs)

**Comment by Gillibald** [comment]
- [ ] Slow performance scrolling a file on macOS

**Comment by danipen** [comment]
- [ ] We're leaking thousands of `ForegroundTextTransformations` when scrolling a document.

**Comment by Gillibald** [comment]
Are we leaking TextLines as well?

**Comment by danipen** [comment]
No. It seems we're only leaking `ForegroundTextTransformation` objects in some kind of cycle.
![image](https://user-images.githubusercontent.com/501613/183261351-cc714049-546f-46fa-8948-c146c4046867.png)

**Comment by HendrikMennen** [comment]
Just tried this, most things work.
On thing I noticed is folding is broken:
```
 Specified argument was out of the range of valid values.
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Avalonia.Media.TextFormatting.Unicode.Codepoint.ReadAt(ReadOnlySlice`1 text, Int32 index, Int32& count) in /_/src/Avalonia.Base/Media/TextFormatting/Unicode/Codepoint.cs:line 170
   at Avalonia.Media.TextFormatting.Unicode.LineBreakEnumerator.NextCharClass() in /_/src/Avalonia.Base/Media/TextFormatting/Unicode/LineBreakEnumerator.cs:line 295
   at Avalonia.Media.TextFormatting.Unicode.LineBreakEnumerator.MoveNext() in /_/src/Avalonia.Base/Media/TextFormatting/Unicode/LineBreakEnumerator.cs:line 57
   at Avalonia.Media.TextFormatting.TextFormatterImpl.TryGetLineBreak(TextRun textRun, LineBreak& lineBreak) in /_/src/Avalonia.Base/Media/TextFormatting/TextFormatterImpl.cs:line 454
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FetchTextRuns(ITextSource textSource, Int32 firstTextSourceIndex, TextEndOfLine& endOfLine, Int32& textSourceLength) in /_/src/Avalonia.Base/Media/TextFormatting/TextFormatterImpl.cs:line 407
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FormatLine(ITextSource textSource, Int32 firstTextSourceIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak) in /_/src/Avalonia.Base/Media/TextFormatting/T
extFormatterImpl.cs:line 62
   at AvaloniaEdit.Rendering.TextView.BuildVisualLine(DocumentLine documentLine, TextRunProperties globalTextRunProperties, VisualLineTextParagraphProperties paragraphProperties, VisualLineElementGenerator[] elementGeneratorsArray, IVisualLineTransformer[] lineTra
nsformersArray, Size availableSize) in C:\Users\hmenn\source\repos\VHDP\AvaloniaEdit\src\AvaloniaEdit\Rendering\TextView.cs:line 1122
   at AvaloniaEdit.Rendering.TextView.CreateAndMeasureVisualLines(Size availableSize) in C:\Users\hmenn\source\repos\VHDP\AvaloniaEdit\src\AvaloniaEdit\Rendering\TextView.cs:line 1011
   at AvaloniaEdit.Rendering.TextView.MeasureOverride(Size availableSize) in C:\Users\hmenn\source\repos\VHDP\AvaloniaEdit\src\AvaloniaEdit\Rendering\TextView.cs:line 941
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 520
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 385
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control) in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 274
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass() in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 250
   at Avalonia.Layout.LayoutManager.InnerLayoutPass() in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 232
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass() in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 145
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 287
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 214
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at VHDPlus.Program.Main(String[] args) in C:\Users\hmenn\source\repos\VHDP\VHDPlus\Program.cs:line 95

```

**Comment by Gillibald** [comment]
Could you provide the actual text you tried to display?

**Comment by HendrikMennen** [comment]
The text is not relevant here I guess.
It's simply the folding feature that does not work yet:
![image](https://user-images.githubusercontent.com/25281882/188463429-13387908-cd4c-4345-ae32-df7b0abb30b5.png)

**Comment by Gillibald** [comment]
As long it is simply reproducible for me this should be simple to fix

**Comment by danipen** [comment]
BTW @Gillibald this one is fixed with Avalonia 11:

> Slow performance scrolling a file on macOS

So feel free to mark it as completed (checked).

**Comment by Gillibald** [comment]
Currently not out of the box. There are plans to introduce an API that allows to enable / disable certain font features like liga etc.

If you don't want ligatures at all you need to register a custom text shaper that disables this feature or use a font that does not have this ligature.

**Comment by HendrikMennen** [comment]
Thank you I just changed to a different font. 
One more thing I noticed is the flickering in this version. 
Seems like before providing a new frame, the old frame is cleared first. 
Here a gif a 0.5x speed:
![ezgif-4-963b4f8429](https://user-images.githubusercontent.com/25281882/188890474-14a5f0ae-34df-480e-a4f2-0d6ea283ceef.gif)

**Comment by danipen** [comment]
Yes. That flickering is new in Avalonia 11. 

Probably related (or same issue) to this: https://github.com/AvaloniaUI/Avalonia/issues/8830

**Comment by danipen** [comment]
The IBeam mouse pointer is lost when hovering text:
![mouse-pointer-lost](https://user-images.githubusercontent.com/501613/189218246-0df7141c-452e-4d36-8521-f2a4a3fe642c.gif)

**Comment by danipen** [comment]
Unfortunately the following PR doesn't fix the flickering issue while selecting text: https://github.com/AvaloniaUI/Avalonia/pull/8918

@Gillibald any idea of what's going on there? This didn't happen on the stable `0.10.x`
![blinking](https://user-images.githubusercontent.com/501613/189219284-cb3738d2-f8c4-4184-bf75-d5835ed5960b.gif)

**Comment by Gillibald** [comment]
Will have a look next week. Probably some issue with the way VisualLine is being rendered.

**Comment by Gillibald** [comment]
@HendrikMennen I can't repro the folding issue with AvaloniaEdit.Demo I need a repro to fix your issue

**Comment by Gillibald** [comment]
@danipen #252

**Comment by HendrikMennen** [comment]
Its quite weird: For testing I used this folding strategy: https://github.com/icsharpcode/AvalonEdit/blob/master/ICSharpCode.AvalonEdit.Sample/BraceFoldingStrategy.cs

This works:
![image](https://user-images.githubusercontent.com/25281882/189676366-b8b32305-cbf8-478f-95d9-a749a66fa9a8.png)
These examples crash:
![image](https://user-images.githubusercontent.com/25281882/189676499-d964e3c4-8a63-47c7-8a5e-620196c38f78.png)
![image](https://user-images.githubusercontent.com/25281882/189675460-a4faca8d-7b62-477b-bc84-ad6ca3b2e2f7.png)
![image](https://user-images.githubusercontent.com/25281882/189675699-a07ff576-c325-4abe-8e28-2acbf0ad2ea4.png)

I guess you used the builtin XmlFoldingStrategy to reproduce?
In that case use this xml code:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  CRASH here ! <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <WarningsNotAsErrors>0612,0618</WarningsNotAsErrors>
	<PackageId>Avalonia.AvaloniaEdit</PackageId>
  </PropertyGroup>

</Project>
```

**Comment by Gillibald** [comment]
Y I was using the XmlFoldingStrategy. Let me try your implementation.
