### ISSUE TITLE
Folding crash

### ISSUE THREAD

**Issue by HendrikMennen** [AvaloniaUI/AvaloniaEdit#272]
To reproduce, simply open the xml example and put `<!--` in front of one of the nodes, then collapse it.
![image](https://user-images.githubusercontent.com/25281882/195565064-e2ade9c7-f8d2-4783-b378-c0ff4cf266c9.png)
```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Avalonia.Media.TextFormatting.Unicode.Codepoint.ReadAt(ReadOnlySlice`1 text, Int32 index, Int32& count) in /_/src/Avalonia.Base/Media/TextFormatting/Unicode/Codepoint.cs:line 170
   at Avalonia.Media.TextFormatting.Unicode.LineBreakEnumerator.NextCharClass() in /_/src/Avalonia.Base/Media/TextFormatting/Unicode/LineBreakEnumerator.cs:line 295
   at Avalonia.Media.TextFormatting.Unicode.LineBreakEnumerator.MoveNext() in /_/src/Avalonia.Base/Media/TextFormatting/Unicode/LineBreakEnumerator.cs:line 57
   at Avalonia.Media.TextFormatting.TextFormatterImpl.TryGetLineBreak(TextRun textRun, LineBreak& lineBreak) in /_/src/Avalonia.Base/Media/TextFormatting/TextFormatterImpl.cs:line 454
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FetchTextRuns(ITextSource textSource, Int32 firstTextSourceIndex, TextEndOfLine& endOfLine, Int32& textSourceLength) in /_/src/Avalonia.Base/Media/TextFormatting/TextFormatterImpl.cs:line 407
   at Avalonia.Media.TextFormatting.TextFormatterImpl.FormatLine(ITextSource textSource, Int32 firstTextSourceIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak) in /_/src/Avalonia.Base/Media/TextFormatting/TextFormatterImpl.cs:line 62
   at AvaloniaEdit.Rendering.TextView.BuildVisualLine(DocumentLine documentLine, TextRunProperties globalTextRunProperties, VisualLineTextParagraphProperties paragraphProperties, IReadOnlyList`1 elementGeneratorsArray, IReadOnlyList`1 lineTransformersArray, Size availableSize) in /home/hendrikm/RiderProjects/AvaloniaEdit/src/AvaloniaEdit/Rendering/TextView.cs:line 1092
   at AvaloniaEdit.Rendering.TextView.CreateAndMeasureVisualLines(Size availableSize) in /home/hendrikm/RiderProjects/AvaloniaEdit/src/AvaloniaEdit/Rendering/TextView.cs:line 976
   at AvaloniaEdit.Rendering.TextView.MeasureOverride(Size availableSize) in /home/hendrikm/RiderProjects/AvaloniaEdit/src/AvaloniaEdit/Rendering/TextView.cs:line 909
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 520
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 385
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control) in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 274
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass() in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 250
   at Avalonia.Layout.LayoutManager.InnerLayoutPass() in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 232
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass() in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 145
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 169
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 245
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at AvaloniaEdit.Demo.Program.Main(String[] args) in /home/hendrikm/RiderProjects/AvaloniaEdit/src/AvaloniaEdit.Demo/Program.cs:line 13

```

**Comment by danipen** [comment]
@Gillibald this is on the TextFormatterImpl ... do you think it may be fixed with the last text engine changes (or is not related)?

**Comment by Gillibald** [comment]
Let me verify this

**Comment by danipen** [comment]
It seems to be the same issue. 

BTW I guess syntax highlighting is not working in wasm, right?

**Comment by Numpsy** [comment]
> BTW I guess syntax highlighting is not working in wasm, right?

I hadn't tried it after seeing #201, but I just gave it a quick try, and it appeared to cause Edge to get stuck when setting the grammar (as in, it just sat there using 25% cpu until I killed it)

**Comment by danipen** [comment]
Ok. That means it's not working yet ☺️

**Comment by danipen** [comment]
@Numpsy @HendrikMennen could you verify if #273 fixes the issue? Thanks!
