### ISSUE TITLE
Navigating with arrow keys causes application to crash

### ISSUE THREAD

**Issue by pracsec** [AvaloniaUI/AvaloniaEdit#301]
When using AvaloniaEdit, navigating around with arrow keys causes the application to crash. Here is the output of the unhandled exception:

```
{"value must not be negative (Parameter 'visualColumn')
Actual value was -1."}
ParamName	"visualColumn"	string
```

Stack Trace

```
"   at AvaloniaEdit.Utils.ThrowUtil.CheckNotNegative(Int32 val, String parameterName)
   at AvaloniaEdit.Rendering.VisualLine.GetRelativeOffset(Int32 visualColumn)
   at AvaloniaEdit.Rendering.VisualLine.GetTextViewPosition(Int32 visualColumn)
   at AvaloniaEdit.Editing.CaretNavigationCommandHandler.GetUpDownCaretPosition(TextView textView, TextViewPosition caretPosition, CaretMovementType direction, VisualLine visualLine, TextLine textLine, Boolean enableVirtualSpace, Double& xPos)
   at AvaloniaEdit.Editing.CaretNavigationCommandHandler.GetNewCaretPosition(TextView textView, TextViewPosition caretPosition, CaretMovementType direction, Boolean enableVirtualSpace, Double& desiredXPos)
   at AvaloniaEdit.Editing.CaretNavigationCommandHandler.MoveCaret(TextArea textArea, CaretMovementType direction)
   at AvaloniaEdit.Editing.CaretNavigationCommandHandler.<>c__DisplayClass9_0.<OnMoveCaret>b__0(Object target, ExecutedRoutedEventArgs args)
   at AvaloniaEdit.RoutedCommandBinding.DoExecuted(Object sender, ExecutedRoutedEventArgs e)
   at AvaloniaEdit.RoutedCommand.<>c__DisplayClass9_0.<ExecutedEventHandler>b__1(RoutedCommandBinding c)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at AvaloniaEdit.RoutedCommand.ExecutedEventHandler(IRoutedCommandBindable control, ExecutedRoutedEventArgs args)
   at System.Reactive.Subjects.Subject`1.OnNext(T value)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at AvaloniaEdit.RoutedCommand.Execute(Object parameter, IInputElement target)
   at AvaloniaEdit.RoutedCommand.System.Windows.Input.ICommand.Execute(Object parameter)
   at AvaloniaEdit.Editing.TextAreaInputHandler.TextAreaOnKeyDown(Object sender, KeyEventArgs keyEventArgs)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.KeyboardDevice.ProcessRawEvent(RawInputEventArgs e)
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at SpecterInsight.UI.Program.Main(String[] args) in C:\\Users\\helpdesk\\Desktop\\Workspace\\repos\\SpecterInsight\\src\\Clients\\SpecterInsight.UI\\Program.cs:line 27"
```

**Comment by pracsec** [comment]
After some thought, I wanted to add that this problem seems to come up in the control that is displaying markdown syntax highlighted data. It could be an issue with indexing related to creating code blacks with the three backticks.
