### ISSUE TITLE
Bug: AvaloniaEdit crashes when cutting text

### ISSUE THREAD

**Issue by pracsec** [AvaloniaUI/AvaloniaEdit#303]
I ran into another crash after using the "cut" command to cut all of the text out of an AvaloniaEdit control.

Exception:

```
"Operation is not valid due to the current state of the object."
```

StackTrace:

```
"   at AvaloniaEdit.Document.DocumentLine.get_LineNumber()
   at AvaloniaEdit.Editing.LineNumberMargin.Render(DrawingContext drawingContext)
   at Avalonia.Rendering.Composition.CompositingRenderer.Update()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at SpecterInsight.UI.Program.Main(String[] args) in C:\\Users\\helpdesk\\Desktop\\Workspace\\repos\\SpecterInsight\\src\\Clients\\SpecterInsight.UI\\Program.cs:line 27"
```

**Comment by danipen** [comment]
Are you calling cut command from the UI thread?

**Comment by pracsec** [comment]
I'm using the built in Cut command from the right-click context menu, so I think so.

**Comment by pracsec** [comment]
I think the line_number was -1 which triggered the exception.

**Comment by danipen** [comment]
Can you reproduce the issue with the Demo application?

**Comment by pracsec** [comment]
Hmmm, I have not been able to reproduce the behavior in the demo application, but I do get a crash whenever I do the following in a blank AvaloniaEdit with Markdown syntax highlighting enabled.

Type 3 backticks
return
return
type 3 backticks
up arrow

That set of actions reliably triggers a crash in my application (AvaloniaEdit 11.0.0-preview1).

**Comment by pracsec** [comment]
Maybe its something weird with my implementation of TextEditor.

```csharp
using Avalonia;
using Avalonia.Controls;
using Avalonia.Data;
using Avalonia.Input;
using Avalonia.Media;
using AvaloniaEdit;
using AvaloniaEdit.Document;
using AvaloniaEdit.Editing;
using AvaloniaEdit.Folding;
using AvaloniaEdit.Rendering;
using AvaloniaEdit.TextMate;
using AvaloniaEdit.TextMate.Grammars;
using SpecterInsight.UI.Models;
using SpecterInsight.UI.Views.Controls;
using System;
using System.Collections.Generic;

namespace SpecterInsight.UI.Views {
    using Pair = KeyValuePair<int, Control>;

    public partial class CodeEditorControl : TextEditor {
        private FoldingManager _foldingManager;
        private readonly TextMate.Installation _textMateInstallation;
        private ElementGenerator _generator = new ElementGenerator();
        private RegistryOptions _registryOptions;
        private int _currentTheme = (int)ThemeName.DarkPlus;

        private string _language = string.Empty;
        public string Language {
            get { return this._language; }
            set {
                this.SetAndRaise(LanguageProperty, ref this._language, value);
                this.SetLanguage(value);
            }
        }

        public static readonly DirectProperty<CodeEditorControl, string> LanguageProperty =
            AvaloniaProperty.RegisterDirect<CodeEditorControl, string>(
                nameof(Language),
                o => o.Language,
                (o, v) => o.Language = v,
                unsetValue: ".md",
                defaultBindingMode: BindingMode.OneWay);

        public CodeEditorControl() {
            InitializeComponent();
            this.ShowLineNumbers = true;
            this.ContextMenu = new ContextMenu {
                Items = new List<MenuItem>
                {
                    new MenuItem { Header = "Copy", InputGesture = new KeyGesture(Key.C, KeyModifiers.Control) },
                    new MenuItem { Header = "Paste", InputGesture = new KeyGesture(Key.V, KeyModifiers.Control) },
                    new MenuItem { Header = "Cut", InputGesture = new KeyGesture(Key.X, KeyModifiers.Control) }
                }
            };

            this.Options.ShowBoxForControlCharacters = true;
            //this.TextArea.IndentationStrategy = new AvaloniaEdit.Indentation.CSharp.CSharpIndentationStrategy(this.Options);
            this.TextArea.RightClickMovesCaret = true;

            this.TextArea.TextView.ElementGenerators.Add(_generator);

            this._registryOptions = new RegistryOptions((ThemeName)_currentTheme);

            this._textMateInstallation = this.InstallTextMate(_registryOptions);

            //this.SetLanguage(".ps1");

            this.Document = new TextDocument(string.Empty);
            this.TextArea.TextView.LineTransformers.Add(new UnderlineAndStrikeThroughTransformer());

            this._currentTheme = (int)ThemeName.DarkPlus;
            this._textMateInstallation.SetTheme(_registryOptions.LoadTheme((ThemeName)_currentTheme));
        }

        public void SetLanguage(string extension) {
            if (string.IsNullOrEmpty(extension)) {
                return;
            }

            Language language = this._registryOptions.GetLanguageByExtension(extension);
            string scopeName = this._registryOptions.GetScopeByLanguageId(language.Id);
            this._textMateInstallation.SetGrammar(scopeName);
        }

        class ElementGenerator : VisualLineElementGenerator, IComparer<Pair> {
            public List<Pair> controls = new List<Pair>();

            /// <summary>
            /// Gets the first interested offset using binary search
            /// </summary>
            /// <returns>The first interested offset.</returns>
            /// <param name="startOffset">Start offset.</param>
            public override int GetFirstInterestedOffset(int startOffset) {
                int pos = controls.BinarySearch(new Pair(startOffset, null), this);
                if (pos < 0)
                    pos = ~pos;
                if (pos < controls.Count)
                    return controls[pos].Key;
                else
                    return -1;
            }

            public override VisualLineElement ConstructElement(int offset) {
                int pos = controls.BinarySearch(new Pair(offset, null), this);
                if (pos >= 0)
                    return new InlineObjectElement(0, controls[pos].Value);
                else
                    return null;
            }

            int IComparer<Pair>.Compare(Pair x, Pair y) {
                return x.Key.CompareTo(y.Key);
            }
        }

        class UnderlineAndStrikeThroughTransformer : DocumentColorizingTransformer {
            protected override void ColorizeLine(DocumentLine line) {
                if (line.LineNumber == 2) {
                    string lineText = this.CurrentContext.Document.GetText(line);

                    int indexOfUnderline = lineText.IndexOf("underline");
                    int indexOfStrikeThrough = lineText.IndexOf("strikethrough");

                    if (indexOfUnderline != -1) {
                        ChangeLinePart(
                            line.Offset + indexOfUnderline,
                            line.Offset + indexOfUnderline + "underline".Length,
                            visualLine => {
                                if (visualLine.TextRunProperties.TextDecorations != null) {
                                    var textDecorations = new TextDecorationCollection(visualLine.TextRunProperties.TextDecorations) { TextDecorations.Underline[0] };

                                    visualLine.TextRunProperties.SetTextDecorations(textDecorations);
                                } else {
                                    visualLine.TextRunProperties.SetTextDecorations(TextDecorations.Underline);
                                }
                            }
                        );
                    }

                    if (indexOfStrikeThrough != -1) {
                        ChangeLinePart(
                            line.Offset + indexOfStrikeThrough,
                            line.Offset + indexOfStrikeThrough + "strikethrough".Length,
                            visualLine => {
                                if (visualLine.TextRunProperties.TextDecorations != null) {
                                    var textDecorations = new TextDecorationCollection(visualLine.TextRunProperties.TextDecorations) { TextDecorations.Strikethrough[0] };

                                    visualLine.TextRunProperties.SetTextDecorations(textDecorations);
                                } else {
                                    visualLine.TextRunProperties.SetTextDecorations(TextDecorations.Strikethrough);
                                }
                            }
                        );
                    }
                }
            }
        }
    }
}

```

**Comment by danipen** [comment]
Yes, probably the element generator and the transformer causes the issue.

**Comment by pracsec** [comment]
I commented out the element generator code, and it still crashes in the same way described above. This isn't too surprising though because the element generator was copied directly from the Demo App.

**Comment by danipen** [comment]
Maybe the problem is inheriting from TextEditor. Try using composition.

**Comment by pracsec** [comment]
I have removed everything I can possible think of that is non-stock AvaloniaEdit and I still get a crash.

```xml
<avedit:TextEditor Name="DocumentationEditor"
					Background="Black"
					Grid.Row="1"
					Grid.Column="0"
					FontFamily="Cascadia Code,Consolas,Menlo,Monospace"
					Foreground="#D4D4D4"
					HorizontalScrollBarVisibility="Auto"
					VerticalScrollBarVisibility="Visible"
					FontWeight="Light"
					FontSize="10"
					WordWrap="True"
					Document="{Binding Documentation}"
/>
```

**Comment by pracsec** [comment]
If I set TextEditor.Options.ShowEndOfLine = true, the program stops crashing.

**Comment by danipen** [comment]
So can you provide an specific example that reproduces the issue in the demo application (or slightly modifying the demo app)? I ask that because we need a repro case to identify the issue (if any) and fix. Thanks 🙏

**Comment by pracsec** [comment]
Here is a minimal app that crashes for me: https://github.com/pracsec/AvaloniaEditCrashDemo

**Comment by danipen** [comment]
> in the demo application

**Comment by pracsec** [comment]
Alright, I got it working (i.e. crashing in the demo app).

Set WordWrap to true in MainWindow.xaml

```xml
<AvalonEdit:TextEditor Name="Editor"
   FontFamily="Cascadia Code,Consolas,Menlo,Monospace"
   Margin="30"
   Foreground="#D4D4D4"
   HorizontalScrollBarVisibility="Auto"
   VerticalScrollBarVisibility="Visible"
   FontWeight="Light"
   FontSize="14"
   WordWrap="True"/>
```

Next, run the app and choose Markdown (not 100% sure this step matters), then

clear the contents
type 3 backticks
return
return
type 3 backticks
up arrow <--- crashes here

**Comment by danipen** [comment]
Sorry I cannot repro with that instructions:

![no-repro](https://user-images.githubusercontent.com/501613/217169664-7a45ac67-e83b-4fa4-bab7-6cb86749614e.gif)
