### ISSUE TITLE
Can't load styles for AvaloniaEdit

### ISSUE THREAD

**Issue by JaggerJo** [AvaloniaUI/AvaloniaEdit#322]
Just tried to use a TextEditor in Avalonia `11.0.0-preview6` and loading the styles for the TextEditor fails:

```xml
<PackageReference Include="AvaloniaEdit.TextMate" Version="11.0.0-preview5" />
<PackageReference Include="AvaloniaEdit.TextMate.Grammars" Version="0.10.12" />
<PackageReference Include="Avalonia.AvaloniaEdit" Version="11.0.0-preview5" />        
```

```fsharp
type App() =
    inherit Application()

    override this.Initialize() =
        this.Styles.Add (FluentTheme())
        this.RequestedThemeVariant <- Styling.ThemeVariant.Dark

        this.Styles.Add(StyleInclude(baseUri = null, Source = Uri("avares://AvaloniaEdit/Themes/Fluent/AvaloniaEdit.xaml")))
```

```
Avalonia.Markup.Xaml.XamlLoadException: No precompiled XAML found for avares://AvaloniaEdit/Themes/Fluent/AvaloniaEdit.xaml (baseUri: ), make sure to specify x:Class and include your XAML file as AvaloniaResource
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(IServiceProvider sp, Uri uri, Uri baseUri) in /_/src/Markup/Avalonia.Markup.Xaml/AvaloniaXamlLoader.cs:line 115
   at Avalonia.Markup.Xaml.Styling.StyleInclude.get_Loaded() in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 63
   at Avalonia.Markup.Xaml.Styling.StyleInclude.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 105
   at Avalonia.Styling.Styles.InternalAdd(IList items, IResourceHost owner) in /_/src/Avalonia.Base/Styling/Styles.cs:line 265
   at Avalonia.Styling.Styles.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in /_/src/Avalonia.Base/Styling/Styles.cs:line 301
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 700
   at Avalonia.Collections.AvaloniaList`1.Add(T item) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 205
   at Avalonia.Styling.Styles.Add(IStyle item) in /_/src/Avalonia.Base/Styling/Styles.cs:line 165
   at Avalonia.FuncUI.AvaloniaExtensions.Styles.Load(Styles this, String source) in /Users/josuajaeger/sources/Avalonia.FuncUI/src/Avalonia.FuncUI/Helpers.fs:line 20
   at Examples.CounterApp.App.Initialize() in /Users/josuajaeger/sources/Avalonia.FuncUI/src/Avalonia.FuncUI.Docs/Program.fs:line 52
   at Avalonia.AppBuilder.Setup() in /_/src/Avalonia.Controls/AppBuilder.cs:line 263
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilder.cs:line 162
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 213
   at Examples.CounterApp.Program.main(String[] args) in /Users/josuajaeger/sources/Avalonia.FuncUI/src/Avalonia.FuncUI.Docs/Program.fs:line 65
```

**Comment by JaggerJo** [comment]
It works on master, guess all that's left to do is release a new version.

**Comment by danipen** [comment]
@Takoooooo

**Comment by Numpsy** [comment]
You might want avares://AvaloniaEdit/AvaloniaEdit.xaml rather than avares://AvaloniaEdit/Themes/Fluent/AvaloniaEdit.xaml in previous versions

**Comment by Numpsy** [comment]
you might also want TextMateSharp.Grammars rather than AvaloniaEdit.TextMate.Grammars for the latest versions

**Comment by JaggerJo** [comment]
ahaa, so I guess I can close this. @Numpsy thanks!

**Comment by Takoooooo** [comment]
@danipen https://github.com/AvaloniaUI/AvaloniaEdit/releases/tag/11.0.0-preview6 Done
