### ISSUE TITLE
NullReferenceException when searching

### ISSUE THREAD

**Issue by chenjing1294** [AvaloniaUI/AvaloniaEdit#326]
OS:macOS 13.3.1
Error when using Command + F to bring up the search panel:
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Native.AvaloniaNativeTextInputMethod.OnCursorRectangleChanged(Object sender, EventArgs e) in /_/src/Avalonia.Native/AvaloniaNativeTextInputMethod.cs:line 63
   at AvaloniaEdit.Editing.TextArea.TextAreaTextInputMethodClient.SetTextArea(TextArea textArea)
   at AvaloniaEdit.Editing.TextArea.OnLostFocus(RoutedEventArgs e)
   at Avalonia.Input.InputElement.<>c.<.cctor>b__32_1(InputElement x, RoutedEventArgs e) in /_/src/Avalonia.Base/Input/InputElement.cs:line 217
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value) in /_/src/Avalonia.Base/Reactive/LightweightObservableBase.cs:line 149
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Base/Interactivity/EventRoute.cs:line 118
   at Avalonia.Interactivity.EventRoute.RaiseEvent(Interactive source, RoutedEventArgs e) in /_/src/Avalonia.Base/Interactivity/EventRoute.cs:line 79
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Base/Interactivity/Interactive.cs:line 126
   at Avalonia.Input.KeyboardDevice.SetFocusedElement(IInputElement element, NavigationMethod method, KeyModifiers keyModifiers) in /_/src/Avalonia.Base/Input/KeyboardDevice.cs:line 150
   at Avalonia.Input.FocusManager.SetFocusedElement(IFocusScope scope, IInputElement element, NavigationMethod method, KeyModifiers keyModifiers) in /_/src/Avalonia.Base/Input/FocusManager.cs:line 142
   at Avalonia.Input.FocusManager.Focus(IInputElement control, NavigationMethod method, KeyModifiers keyModifiers) in /_/src/Avalonia.Base/Input/FocusManager.cs:line 70
   at Avalonia.Input.InputElement.Focus() in /_/src/Avalonia.Base/Input/InputElement.cs:line 500
   at AvaloniaEdit.Search.SearchPanel.Reactivate()
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 193
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.Native.PlatformThreadingInterface.SignaledCallback.Signaled(Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 39
   at Avalonia.Native.Interop.Impl.__MicroComIAvnSignaledCallbackVTable.Signaled(Void* this, Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/Interop.Generated.cs:line 5072
--- End of stack trace from previous location ---
   at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 90
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 122
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 214
   at ZooKeeperAssistant.Program.Main(String[] args) in /Users/chenjing/RiderProjects/zookeeper-assistant-avalonia/ZooKeeperAssistant/Program.cs:line 23

Process finished with exit code 134.
```

**Comment by Gillibald** [comment]
Will be fixed in the next preview
