### ISSUE TITLE
Avalonia 11.0.0 breaks WASM

### ISSUE THREAD

**Issue by HendrikMennen** [AvaloniaUI/AvaloniaEdit#351]
At RC1.1 WASM was working with avaloniaedit.
Now it is broken:

```
Error: One or more errors occurred. (Could not load type of field 'AvaloniaEdit.Editing.TextArea:_imClient' (2) due to: Could not resolve type with token 01000145 from typeref (expected class 'Avalonia.Input.TextInput.TextInputMethodClient' in assembly 'Avalonia.Base, Version=11.0.0.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b') assembly:Avalonia.Base, Version=11.0.0.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b type:Avalonia.Input.TextInput.TextInputMethodClient member:(null))
    at jo (dotnet.js:5:37939)
    at Object.Oo (dotnet.js:5:37538)
    at _mono_wasm_marshal_promise (dotnet.js:7693:70)
    at do_icall (do_icall (dotnet.wasm:0x5ac8e3))
    at do_icall_wrapper (do_icall_wrapper (dotnet.wasm:0x5ab8e8))
    at interp_exec_method (interp_exec_method (dotnet.wasm:0x59c454))
    at interp_runtime_invoke (interp_runtime_invoke (dotnet.wasm:0x59b25a))
    at mono_jit_runtime_invoke (mono_jit_runtime_invoke (dotnet.wasm:0x7932a8))
    at do_runtime_invoke (do_runtime_invoke (dotnet.wasm:0x63210b))
    at mono_runtime_try_invoke (mono_runtime_try_invoke (dotnet.wasm:0x63289e))
```

I just experimented with wasm a bit so far and don't know a lot about it, maybe someone here knows why the change to TextInputMethodClient broke wasm support.

**Comment by danipen** [comment]
@Gillibald seems an IME issue too. Any ideas?

**Comment by HendrikMennen** [comment]
@Gillibald Can confirm this happens with a clean rebuild too

**Comment by Gillibald** [comment]
My guess is that the type is somehow being trimmed

**Comment by HendrikMennen** [comment]
Seems to work now with newest updates
